### ISSUE TITLE
DESCRIBE seems to return reverse properties

### ISSUE THREAD

**Issue by ktk** [lindas-uc/lindas-issues#12]
When I execute against http://lindas-data.ch/sparql

```
DESCRIBE <http://environment.data.admin.ch/ubd/28/station/blBAS>
```

I seem to get back all triples as well that use this URI as object, which is in this case not a good idea as this can result in really large answers due to the nature of the dataset (Data Cube).

How can I change the behavior of Virtuoso?

**Comment by martin-voigt** [comment]
Hi,
just define the **describe mode**, so execute

`DEFINE sql:describe-mode "SPO" DESCRIBE <http://environment.data.admin.ch/ubd/28/station/blBAS>`

More inforamtion at http://docs.openlinksw.com/virtuoso/rdfsparql.html#rdfsqlfromsparqldescribe

**Comment by ktk** [comment]
That works fine, thanks!
