### ISSUE TITLE
SPARQL endpoint does not set CORS headers

### ISSUE THREAD

**Issue by ktk** [lindas-uc/lindas-issues#3]
Currently there are no CORS headers sent from the SPARQL endpoint which makes using it from webapps cumbersome

**Comment by martin-voigt** [comment]
Hmm, it was already defined in Virtuoso on test, for /sparql and /sparql-auth. I updated it for productive right now. Please double-check. If not working, we will check the proxy.

**Comment by retog** [comment]
Fixed according to email from @martin-voigt
