### ISSUE TITLE
SPARQL endpoint does not use compression by default

### ISSUE THREAD

**Issue by ktk** [lindas-uc/lindas-issues#4]
The SPARQL endpoint should support HTTP compression to reduce bandwith used

**Comment by retog** [comment]
"use compression by default" might be misleading, it should use compression if and only if the client indicates support with the `Accept-Encoding`header

**Comment by martin-voigt** [comment]
We'll check this tomorrow within our proxy

**Comment by martin-voigt** [comment]
gzip compression is turned on for both systems

**Comment by vzi** [comment]
All responses at both systems are compressed if a request has the header `Accept-Encoding: gzip` and the length of a response exceeds MTU.

**Comment by l00mi** [comment]
Perfect!
Response of our customer: "Heute Morgen ist der Table Viewer brutal schnell!" we will tell them where it comes from.

Unfortunately we again see problems regarding the https://github.com/lindas-uc/lindas-issues/issues/5 ...

**Comment by ktk** [comment]
Confirmed in browser, closing this one
